# Generated by Django 4.1.4 on 2022-12-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='delivery',
            field=models.CharField(choices=[('Physical', 'Physical'), ('immediate', 'Immediate'), ('Twenty_Four_Hours', 'Twentyfourhours'), ('Three_Days', 'Threedays'), ('One_Week', 'Oneweek')], default='immediate', max_length=100),
        ),
    ]
