# Generated by Django 4.1.4 on 2022-12-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_orders_date_created_alter_orders_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
