# Generated by Django 4.1.4 on 2022-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, help_text='Product Image', upload_to='events'),
        ),
    ]
