# Generated by Django 4.1.4 on 2022-12-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Product Image', upload_to='events'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, help_text='Product Image', upload_to='tickets'),
        ),
    ]
