# Generated by Django 4.1.4 on 2022-12-22 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_alter_event_image_alter_ticket_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
