# Generated by Django 4.1.4 on 2022-12-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.OneToOneField(default='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='civil_id',
            field=models.PositiveIntegerField(),
        ),
    ]
