# Generated by Django 4.1.4 on 2022-12-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_profile_id_profile_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='civil_id',
            new_name='civilid',
        ),
    ]
